name: "Docker Publish and Push Action"
description: "Builds Docker images and pushes them to a container registry."

inputs:
  tag:
    description: "Image tag."
    required: true
  version:
    description: "Version."
    required: true
  containerRegistry:
    description: "Container registry name."
    required: true
  registryUsername:
    description: "Container registry username."
    required: true
  registryPassword:
    description: "Container registry password."
    required: true"
  buildScript:
    description: "Path to the build script."
    required: true
  token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Print Docker images
      shell: pwsh
      run: |
        Write-Host "--images--"
        docker images

    - name: Docker Login
      if: ${{ success() && github.event_name != 'pull_request' }}
      shell: bash
      run: |
        echo "${{ inputs.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: set lower case owner name
      shell: bash
      run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

    - name: Docker Build by PowerShell
      if: ${{ success() && github.event_name != 'pull_request' }}
      shell: pwsh
      working-directory: ${{ github.workspace }}
      env:
        DOCKER_REGISTRY: "ghcr.io/${{ env.IMAGE_REPOSITORY }}/"
        IMAGE_TAG: "${{ inputs.tag }}"
        VERSION: "${{ inputs.version }}"
        BUILD_VERSION: "${{ inputs.version }}"
      run: |
        $DebugPreference = 'Continue'
        pwd
        . "${{ inputs.buildScript }}"

    - name: Docker Push
      if: ${{ success() && github.event_name != 'pull_request' }}
      shell: bash
      run: |
        docker push ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ inputs.imageName }}:${{ inputs.tag }}
