name: "Docker Publish and Push Action"
description: "Builds Docker images for multiple platforms and pushes them to a container registry."

inputs:
  tag:
    description: "Image tag."
    required: true
  version:
    description: "Version."
    required: true
  buildScript:
    description: "Path to the build script."
    required: true
  token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU for multi-platform builds
      shell: bash
      run: |
        docker run --rm --privileged tonistiigi/binfmt --install all
    
    - name: Set up Docker Buildx
      shell: bash
      run: |
        docker buildx create --use

    - name: Docker Login
      if: ${{ success() && github.event_name != 'pull_request' }}
      shell: bash
      run: |
        echo "${{ inputs.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: set lower case owner name
      shell: bash
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: "${{ github.repository_owner }}"

    - name: Docker Build and Push by PowerShell
      if: ${{ success() && github.event_name != 'pull_request' }}
      shell: pwsh
      working-directory: ${{ github.workspace }}
      env:
        DOCKER_REGISTRY: "ghcr.io/${{ env.OWNER_LC }}/"
        IMAGE_TAG: "${{ inputs.tag }}"
        VERSION: "${{ inputs.version }}"
        BUILD_VERSION: "${{ inputs.version }}"
      run: |
        $DebugPreference = 'Continue'
        pwd
        . "${{ inputs.buildScript }}"