namespace Application.UseCases.Essences.Dtos;

public sealed record PlayerEssenceDto(
    Guid Id,
    string EssenceDefinitionId,
    string Name,
    int Level,
    int CurrentXp,
    int XpRequiredForNextLevel,
    int NativeRegion,
    int PotentialTier,
    int PotentialLevelCap,
    int AscensionTier,
    int TierLevelCap,
    bool IsEvolved,
    bool IsFavorite,
    int? AttunedSlot,
    bool CanAscend,
    bool CanUpgradePotential,
    bool CanEvolve,
    IReadOnlyList<string> MissingRequirements,
    EssencePotentialInfoDto PotentialInfo,
    EssenceAscendInfoDto AscendInfo,
    EssenceEvolveInfoDto EvolveInfo,
    IReadOnlyList<EssenceAttributeBonusDto> CurrentAttributeBonuses,
    EssenceAbilityDto ActiveAbility,
    EssenceAbilityDto PassiveAbility);
