// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.LL;

#nullable disable

namespace Persistence.LL.Migrations
{
    [DbContext(typeof(LLDbContext))]
    [Migration("20260406114229_BaseMigration")]
    partial class BaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Abilities.AbilityId", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id", "EntityId");

                    b.ToTable("AbilityIds");
                });

            modelBuilder.Entity("Domain.Models.Attributes.EntityAttribute", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("EntityId", "AttributeType");

                    b.ToTable("EntityAttributes");
                });

            modelBuilder.Entity("Domain.Models.Attributes.Modifiers.InstanceAttributeModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EquipmentSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModifierType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentSnapshotId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("InstanceAttributeModifier");
                });

            modelBuilder.Entity("Domain.Models.Attributes.Modifiers.ItemAttributeModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<string>("ItemBaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModifierType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemBaseId");

                    b.ToTable("ItemAttributeModifier");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterActionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterActionId")
                        .IsUnique();

                    b.ToTable("ActionDetails");

                    b.HasDiscriminator<int>("ActionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ArenaTicketStatus", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentTickets")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastTicketUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId");

                    b.ToTable("ArenaTicketStatus");
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ColosseumMatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterAId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterAName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CharacterARatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterARatingBefore")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterBId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterBName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CharacterBRatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterBRatingBefore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("WinnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterBId");

                    b.ToTable("ColosseumMatches");
                });

            modelBuilder.Entity("Domain.Models.Dungeons.Runs.DungeonRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRoomIndex")
                        .HasColumnType("integer");

                    b.Property<string>("DungeonDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DungeonRuns");
                });

            modelBuilder.Entity("Domain.Models.Dungeons.Runs.RoomInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DungeonRunId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("EncounterIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("EventOutcome")
                        .HasColumnType("integer");

                    b.Property<int>("RoomIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DungeonRunId");

                    b.ToTable("RoomInstance");
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Templates.StatOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Additive")
                        .HasColumnType("real");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Multiplier")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.ToTable("StatOverride");
                });

            modelBuilder.Entity("Domain.Models.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasDiscriminator<int>("EntityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Essences.Essence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveAbilityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassiveAbilityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Essences");
                });

            modelBuilder.Entity("Domain.Models.Essences.EssenceSlots.EssenceSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EssenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotState")
                        .HasColumnType("integer");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EssenceId");

                    b.ToTable("EssenceSlots");
                });

            modelBuilder.Entity("Domain.Models.Guilds.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildBuildingUpgrade", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingUpgradeDefinitionId")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "BuildingUpgradeDefinitionId");

                    b.ToTable("GuildBuildingUpgrade");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildInvite", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInvite")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildMember", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildResource", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<int>("Resource")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "Resource");

                    b.ToTable("GuildResource");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Domain.Models.Inventories.InventoryItem", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId", "ItemInstanceId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.Slots.EquipmentSlot", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("EquipmentSlotType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EquipmentInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("EntityId", "EquipmentSlotType");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("Domain.Models.Items.ItemBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ItemBases");

                    b.HasDiscriminator<int>("ItemType").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Items.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemBaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemBaseId");

                    b.ToTable("ItemInstances");

                    b.HasDiscriminator<int>("ItemType").HasValue(4);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("LootTableType")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootTableEntry");

                    b.HasDiscriminator<int>("LootTableType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.MarketPlaces.MarketPlaceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("MarketPlaceListings");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.CraftingQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CraftType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CraftingActionDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CraftingActionDetailsId");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("CraftingQueueItems");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Material", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("ItemBaseId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemBaseId");

                    b.HasIndex("ItemId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CraftType")
                        .HasColumnType("integer");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domain.Models.Professions.Gathering.GatheringNodes.GatheringNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("GatheringNodes");
                });

            modelBuilder.Entity("Domain.Models.Professions.Profession", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("integer");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "ProfessionType");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DifficultyTier")
                        .HasColumnType("integer");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<float>>("SpawnProbabilities")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaCreature", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<float>("WeightedSpawnRate")
                        .HasColumnType("real");

                    b.HasKey("AreaId", "CreatureId");

                    b.HasIndex("CreatureId");

                    b.ToTable("AreaCreature");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaGatheringNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<float>("ProcChance")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("LootTableId");

                    b.ToTable("AreaGatheringNode");
                });

            modelBuilder.Entity("Domain.Models.Regions.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Domain.Models.Snapshots.CharacterSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("ActiveEssenceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterSnapshots");
                });

            modelBuilder.Entity("Domain.Models.Snapshots.EntityAttributeSnapshot", b =>
                {
                    b.Property<Guid>("CharacterSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("CharacterSnapshotId", "AttributeType");

                    b.ToTable("EntityAttributeSnapshot");
                });

            modelBuilder.Entity("Domain.Models.Snapshots.EquipmentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentInstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLevelingItem")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMasterpiece")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemBaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemXp")
                        .HasColumnType("integer");

                    b.Property<int?>("Potential")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSnapshotId");

                    b.ToTable("EquipmentSnapshot");
                });

            modelBuilder.Entity("Domain.Models.Soulstones.CharacterSoulstoneUpgrade", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoulstoneUpgradeDefinitionId")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "SoulstoneUpgradeDefinitionId");

                    b.ToTable("CharacterSoulstoneUpgrades");
                });

            modelBuilder.Entity("Domain.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNameEdited")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Users.ExternalLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Domain.Models.Users.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CombatActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("CharacterTeam")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasIndex("AreaId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CraftingActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.GatheringActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("integer");

                    b.HasIndex("LootTableId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.Property<int>("ArenaRating")
                        .HasColumnType("integer");

                    b.Property<long>("Cinders")
                        .HasColumnType("bigint");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<long>("Soulstones")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.Property<int>("Archetype")
                        .HasColumnType("integer");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DamageProfile")
                        .HasColumnType("integer");

                    b.Property<int>("DefenseProfile")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasIndex("LootTableId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.Entities.NPCs.NPC", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentBase", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemBase");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<int?>("GatheringType")
                        .HasColumnType("integer");

                    b.Property<int>("Magnitude")
                        .HasColumnType("integer");

                    b.Property<int>("MagnitudeRange")
                        .HasColumnType("integer");

                    b.Property<float>("ScalingAmount")
                        .HasColumnType("real");

                    b.Property<int>("ScalingAttribute")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItems.EssenceItemBase", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemBase");

                    b.Property<Guid>("EssenceId")
                        .HasColumnType("uuid");

                    b.HasIndex("EssenceId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentInstance", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemInstance");

                    b.Property<bool>("IsLevelingItem")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMasterpiece")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemXp")
                        .HasColumnType("integer");

                    b.Property<int?>("Potential")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItems.EssenceItemInstance", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemInstance");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTable", b =>
                {
                    b.HasBaseType("Domain.Models.LootTables.LootTableEntry");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableItem", b =>
                {
                    b.HasBaseType("Domain.Models.LootTables.LootTableEntry");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ItemId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Attributes.EntityAttribute", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", null)
                        .WithMany("BaseAttributes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Attributes.Modifiers.InstanceAttributeModifier", b =>
                {
                    b.HasOne("Domain.Models.Snapshots.EquipmentSnapshot", null)
                        .WithMany("InstanceModifiers")
                        .HasForeignKey("EquipmentSnapshotId");

                    b.HasOne("Domain.Models.Items.Equipments.EquipmentInstance", null)
                        .WithMany("InstanceModifiers")
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("Domain.Models.Attributes.Modifiers.ItemAttributeModifier", b =>
                {
                    b.HasOne("Domain.Models.Items.Equipments.EquipmentBase", null)
                        .WithMany("AttributeModifiers")
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.ItemBase", "ItemBase")
                        .WithMany()
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("CharacterAction")
                        .HasForeignKey("Domain.Models.CharacterActions.CharacterAction", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", b =>
                {
                    b.HasOne("Domain.Models.CharacterActions.CharacterAction", null)
                        .WithOne("ActionDetails")
                        .HasForeignKey("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", "CharacterActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ArenaTicketStatus", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("ArenaTicketStatus")
                        .HasForeignKey("Domain.Models.Colosseum.ArenaTicketStatus", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ColosseumMatchResult", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", null)
                        .WithMany("ColosseumMatches")
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Dungeons.Runs.RoomInstance", b =>
                {
                    b.HasOne("Domain.Models.Dungeons.Runs.DungeonRun", null)
                        .WithMany("Rooms")
                        .HasForeignKey("DungeonRunId");
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Templates.StatOverride", b =>
                {
                    b.HasOne("Domain.Models.Entities.Creatures.Creature", null)
                        .WithMany("StatOverrides")
                        .HasForeignKey("CreatureId");
                });

            modelBuilder.Entity("Domain.Models.Essences.EssenceSlots.EssenceSlot", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", null)
                        .WithMany("EssenceSlots")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Essences.Essence", "OccupiedEssence")
                        .WithMany("EssenceSlots")
                        .HasForeignKey("EssenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OccupiedEssence");
                });

            modelBuilder.Entity("Domain.Models.Guilds.Guild", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Owner")
                        .WithOne("Guild")
                        .HasForeignKey("Domain.Models.Guilds.Guild", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildBuildingUpgrade", b =>
                {
                    b.HasOne("Domain.Models.Guilds.Guild", "Guild")
                        .WithMany("GuildBuildingUpgrades")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildInvite", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Guilds.Guild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildMember", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Guilds.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildResource", b =>
                {
                    b.HasOne("Domain.Models.Guilds.Guild", null)
                        .WithMany("Resources")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("Domain.Models.Inventories.Inventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Inventories.InventoryItem", b =>
                {
                    b.HasOne("Domain.Models.Inventories.Inventory", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.Slots.EquipmentSlot", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", "Entity")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.Equipments.EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId");

                    b.Navigation("Entity");

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("Domain.Models.Items.ItemInstance", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemBase", "ItemBase")
                        .WithMany("ItemInstances")
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableEntry", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", null)
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Models.MarketPlaces.MarketPlaceListing", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.CraftingQueueItem", b =>
                {
                    b.HasOne("Domain.Models.CharacterActions.CharacterActionDetails.CraftingActionDetails", null)
                        .WithMany("CraftingQueueItems")
                        .HasForeignKey("CraftingActionDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.Equipments.EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Material", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemBase", null)
                        .WithMany("Materials")
                        .HasForeignKey("ItemBaseId");

                    b.HasOne("Domain.Models.Items.ItemBase", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Professions.Crafting.Recipe", null)
                        .WithMany("Materials")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Recipe", b =>
                {
                    b.HasOne("Domain.Models.Items.Equipments.EquipmentBase", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.Professions.Gathering.GatheringNodes.GatheringNode", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Professions.Profession", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", null)
                        .WithMany("Professions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.HasOne("Domain.Models.Regions.Region", null)
                        .WithMany("Areas")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaCreature", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", null)
                        .WithMany("Creatures")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Creatures.Creature", null)
                        .WithMany()
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaGatheringNode", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", "Area")
                        .WithMany("GatheringNodes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Snapshots.EntityAttributeSnapshot", b =>
                {
                    b.HasOne("Domain.Models.Snapshots.CharacterSnapshot", null)
                        .WithMany("BaseAttributes")
                        .HasForeignKey("CharacterSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Snapshots.EquipmentSnapshot", b =>
                {
                    b.HasOne("Domain.Models.Snapshots.CharacterSnapshot", null)
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterSnapshotId");
                });

            modelBuilder.Entity("Domain.Models.Soulstones.CharacterSoulstoneUpgrade", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithMany("CharacterSoulstoneUpgrades")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Users.ExternalLogin", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CombatActionDetails", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.GatheringActionDetails", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItems.EssenceItemBase", b =>
                {
                    b.HasOne("Domain.Models.Essences.Essence", "Essence")
                        .WithMany("EssenceItems")
                        .HasForeignKey("EssenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essence");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableItem", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemBase", "Item")
                        .WithMany("LootTablesItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.Navigation("ActionDetails");
                });

            modelBuilder.Entity("Domain.Models.Dungeons.Runs.DungeonRun", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.Models.Entities.Entity", b =>
                {
                    b.Navigation("BaseAttributes");

                    b.Navigation("EquipmentSlots");

                    b.Navigation("EssenceSlots");
                });

            modelBuilder.Entity("Domain.Models.Essences.Essence", b =>
                {
                    b.Navigation("EssenceItems");

                    b.Navigation("EssenceSlots");
                });

            modelBuilder.Entity("Domain.Models.Guilds.Guild", b =>
                {
                    b.Navigation("GuildBuildingUpgrades");

                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Domain.Models.Items.ItemBase", b =>
                {
                    b.Navigation("ItemInstances");

                    b.Navigation("LootTablesItems");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Recipe", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.Navigation("Creatures");

                    b.Navigation("GatheringNodes");
                });

            modelBuilder.Entity("Domain.Models.Regions.Region", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Domain.Models.Snapshots.CharacterSnapshot", b =>
                {
                    b.Navigation("BaseAttributes");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Domain.Models.Snapshots.EquipmentSnapshot", b =>
                {
                    b.Navigation("InstanceModifiers");
                });

            modelBuilder.Entity("Domain.Models.Users.AppUser", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CraftingActionDetails", b =>
                {
                    b.Navigation("CraftingQueueItems");
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.Navigation("ArenaTicketStatus")
                        .IsRequired();

                    b.Navigation("CharacterAction");

                    b.Navigation("CharacterSoulstoneUpgrades");

                    b.Navigation("ColosseumMatches");

                    b.Navigation("Guild");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Professions");
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.Navigation("StatOverrides");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentBase", b =>
                {
                    b.Navigation("AttributeModifiers");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentInstance", b =>
                {
                    b.Navigation("InstanceModifiers");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTable", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
