// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.LL;

#nullable disable

namespace Persistence.LL.Migrations
{
    [DbContext(typeof(LLDbContext))]
    partial class LLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Abilities.AbilityId", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "EntityId");

                    b.ToTable("AbilityIds");
                });

            modelBuilder.Entity("Domain.Models.Attributes.EntityAttribute", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("EntityId", "AttributeType");

                    b.ToTable("EntityAttributes");
                });

            modelBuilder.Entity("Domain.Models.Attributes.Modifiers.ItemAttributeModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentBaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemBaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModifierType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentBaseId");

                    b.HasIndex("ItemBaseId");

                    b.ToTable("ItemAttributeModifier");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<Guid>("CharacterActionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterActionId")
                        .IsUnique();

                    b.ToTable("ActionDetails");

                    b.HasDiscriminator<int>("ActionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ArenaTicketStatus", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentTickets")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastTicketUpdate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CharacterId");

                    b.ToTable("ArenaTicketStatus");
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ColosseumMatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharacterAName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CharacterBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharacterBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WinnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterBId");

                    b.ToTable("ColosseumMatches");
                });

            modelBuilder.Entity("Domain.Models.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasDiscriminator<int>("EntityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Essences.Essence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveAbilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassiveAbilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Essences");
                });

            modelBuilder.Entity("Domain.Models.Essences.EssenceSlots.EssenceSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EssenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotState")
                        .HasColumnType("int");

                    b.Property<int>("SlotType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EssenceId");

                    b.ToTable("EssenceSlots");
                });

            modelBuilder.Entity("Domain.Models.Guilds.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildInvite", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInvite")
                        .HasColumnType("bit");

                    b.HasKey("GuildId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildMember", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("GuildId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CharacterId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Domain.Models.Inventories.InventoryItem", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId", "ItemInstanceId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.Slots.EquipmentSlot", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<Guid?>("EquipmentInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EntityId", "EquipmentType");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("Domain.Models.Items.ItemBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<bool>("Stackable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ItemBases");

                    b.HasDiscriminator<int>("ItemType").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Items.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemBaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBaseId");

                    b.ToTable("ItemInstances");

                    b.HasDiscriminator<int>("ItemType").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LootTableType")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootTableEntry");

                    b.HasDiscriminator<int>("LootTableType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Masteries.Mastery", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MasteryType")
                        .HasColumnType("int");

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("EntityId", "MasteryType");

                    b.ToTable("Mastery");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.CraftingQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CraftingActionDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("QueueIndex")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CraftingActionDetailsId");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("CraftingQueueItems");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Material", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemBaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemBaseId");

                    b.HasIndex("ItemId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CraftType")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domain.Models.Professions.Gathering.GatheringNodes.GatheringNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("GatheringNodes");
                });

            modelBuilder.Entity("Domain.Models.Professions.Profession", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ProfessionType");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("SpawnProbabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaCreature", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("WeightedSpawnRate")
                        .HasColumnType("real");

                    b.HasKey("AreaId", "CreatureId");

                    b.HasIndex("CreatureId");

                    b.ToTable("AreaCreature");
                });

            modelBuilder.Entity("Domain.Models.Regions.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Domain.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Users.ExternalLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Domain.Models.Users.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CombatActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AreaId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CraftingActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.GatheringActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessionType")
                        .HasColumnType("int");

                    b.HasIndex("LootTableId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.Property<int>("ArenaRating")
                        .HasColumnType("int");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("int");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("LootTableId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.Entities.NPCs.NPC", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentBase", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemBase");

                    b.Property<int>("CombatMastery")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItems.EssenceItemBase", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemBase");

                    b.Property<Guid>("EssenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EssenceId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentInstance", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemInstance");

                    b.Property<bool>("IsLevelingItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMasterpiece")
                        .HasColumnType("bit");

                    b.Property<int>("ItemXp")
                        .HasColumnType("int");

                    b.Property<int?>("Potential")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItems.EssenceItemInstance", b =>
                {
                    b.HasBaseType("Domain.Models.Items.ItemInstance");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTable", b =>
                {
                    b.HasBaseType("Domain.Models.LootTables.LootTableEntry");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableItem", b =>
                {
                    b.HasBaseType("Domain.Models.LootTables.LootTableEntry");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ItemId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Attributes.EntityAttribute", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", null)
                        .WithMany("BaseAttributes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Attributes.Modifiers.ItemAttributeModifier", b =>
                {
                    b.HasOne("Domain.Models.Items.Equipments.EquipmentBase", null)
                        .WithMany("AttributeModifiers")
                        .HasForeignKey("EquipmentBaseId");

                    b.HasOne("Domain.Models.Items.ItemBase", "ItemBase")
                        .WithMany()
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("CharacterAction")
                        .HasForeignKey("Domain.Models.CharacterActions.CharacterAction", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", b =>
                {
                    b.HasOne("Domain.Models.CharacterActions.CharacterAction", null)
                        .WithOne("ActionDetails")
                        .HasForeignKey("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", "CharacterActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ArenaTicketStatus", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("ArenaTicketStatus")
                        .HasForeignKey("Domain.Models.Colosseum.ArenaTicketStatus", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Colosseum.ColosseumMatchResult", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", null)
                        .WithMany("ColosseumMatches")
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Essences.EssenceSlots.EssenceSlot", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", null)
                        .WithMany("EssenceSlots")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Essences.Essence", "OccupiedEssence")
                        .WithMany("EssenceSlots")
                        .HasForeignKey("EssenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OccupiedEssence");
                });

            modelBuilder.Entity("Domain.Models.Guilds.Guild", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Owner")
                        .WithOne("Guild")
                        .HasForeignKey("Domain.Models.Guilds.Guild", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildInvite", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Guilds.Guild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Domain.Models.Guilds.GuildMember", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Guilds.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("Domain.Models.Inventories.Inventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Inventories.InventoryItem", b =>
                {
                    b.HasOne("Domain.Models.Inventories.Inventory", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.Slots.EquipmentSlot", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", "Entity")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.Equipments.EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId");

                    b.Navigation("Entity");

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("Domain.Models.Items.ItemInstance", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemBase", "ItemBase")
                        .WithMany("ItemInstances")
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableEntry", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", null)
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Models.Masteries.Mastery", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", "Entity")
                        .WithMany("Masteries")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.CraftingQueueItem", b =>
                {
                    b.HasOne("Domain.Models.CharacterActions.CharacterActionDetails.CraftingActionDetails", null)
                        .WithMany("CraftingQueueItems")
                        .HasForeignKey("CraftingActionDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.Equipments.EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Material", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemBase", null)
                        .WithMany("Materials")
                        .HasForeignKey("ItemBaseId");

                    b.HasOne("Domain.Models.Items.ItemBase", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Professions.Crafting.Recipe", null)
                        .WithMany("Materials")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Recipe", b =>
                {
                    b.HasOne("Domain.Models.Items.Equipments.EquipmentBase", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.Professions.Gathering.GatheringNodes.GatheringNode", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Professions.Profession", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithMany("Professions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.HasOne("Domain.Models.Regions.Region", null)
                        .WithMany("Areas")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaCreature", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", null)
                        .WithMany("Creatures")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Creatures.Creature", null)
                        .WithMany()
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Users.ExternalLogin", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CombatActionDetails", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.GatheringActionDetails", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItems.EssenceItemBase", b =>
                {
                    b.HasOne("Domain.Models.Essences.Essence", "Essence")
                        .WithMany("EssenceItems")
                        .HasForeignKey("EssenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essence");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableItem", b =>
                {
                    b.HasOne("Domain.Models.Items.ItemBase", "Item")
                        .WithMany("LootTablesItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.Navigation("ActionDetails");
                });

            modelBuilder.Entity("Domain.Models.Entities.Entity", b =>
                {
                    b.Navigation("BaseAttributes");

                    b.Navigation("EquipmentSlots");

                    b.Navigation("EssenceSlots");

                    b.Navigation("Masteries");
                });

            modelBuilder.Entity("Domain.Models.Essences.Essence", b =>
                {
                    b.Navigation("EssenceItems");

                    b.Navigation("EssenceSlots");
                });

            modelBuilder.Entity("Domain.Models.Guilds.Guild", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Domain.Models.Items.ItemBase", b =>
                {
                    b.Navigation("ItemInstances");

                    b.Navigation("LootTablesItems");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Domain.Models.Professions.Crafting.Recipe", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.Navigation("Creatures");
                });

            modelBuilder.Entity("Domain.Models.Regions.Region", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Domain.Models.Users.AppUser", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CraftingActionDetails", b =>
                {
                    b.Navigation("CraftingQueueItems");
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.Navigation("ArenaTicketStatus")
                        .IsRequired();

                    b.Navigation("CharacterAction");

                    b.Navigation("ColosseumMatches");

                    b.Navigation("Guild");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Professions");
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.EquipmentBase", b =>
                {
                    b.Navigation("AttributeModifiers");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTable", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
