// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.LL;

#nullable disable

namespace Persistence.LL.Migrations
{
    [DbContext(typeof(LLDbContext))]
    partial class LLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Abilities.AbilityId", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "EntityId");

                    b.ToTable("AbilityIds");
                });

            modelBuilder.Entity("Domain.Models.Attributes.EntityAttribute", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("EntityId", "AttributeType");

                    b.ToTable("EntityAttributes");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<Guid>("CharacterActionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterActionId")
                        .IsUnique();

                    b.ToTable("ActionDetails");

                    b.HasDiscriminator<int>("ActionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasDiscriminator<int>("EntityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Essences.Essence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveAbilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassiveAbilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Essences");
                });

            modelBuilder.Entity("Domain.Models.GatheringNodes.GatheringNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GatheringType")
                        .HasColumnType("int");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("GatheringNodes");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CharacterId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Domain.Models.Inventories.InventoryItem", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Domain.Models.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<int>("ItemType").HasValue(4);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LootTableType")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootTableEntry");

                    b.HasDiscriminator<int>("LootTableType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("SpawnProbabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaCreature", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("WeightedSpawnRate")
                        .HasColumnType("real");

                    b.HasKey("AreaId", "CreatureId");

                    b.HasIndex("CreatureId");

                    b.ToTable("AreaCreature");
                });

            modelBuilder.Entity("Domain.Models.Regions.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Domain.Models.Users.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("BannedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Users.IPAddresses.IPAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("TimeOfAccess")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("IPAddress");
                });

            modelBuilder.Entity("Domain.Models.Users.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemPurchased")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeOfPurchase")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("EntityEssence", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EssenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EntityId", "EssenceId");

                    b.HasIndex("EssenceId");

                    b.ToTable("EntityEssence");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CombatActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AreaId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.GatheringActionDetails", b =>
                {
                    b.HasBaseType("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails");

                    b.Property<int>("GatheringType")
                        .HasColumnType("int");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("LootTableId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("int");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("LootTableId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.Entities.NPCs.NPC", b =>
                {
                    b.HasBaseType("Domain.Models.Entities.Entity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Items.Equipments.Equipment", b =>
                {
                    b.HasBaseType("Domain.Models.Items.Item");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItem", b =>
                {
                    b.HasBaseType("Domain.Models.Items.Item");

                    b.Property<Guid>("EssenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EssenceId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTable", b =>
                {
                    b.HasBaseType("Domain.Models.LootTables.LootTableEntry");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableItem", b =>
                {
                    b.HasBaseType("Domain.Models.LootTables.LootTableEntry");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ItemId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Models.Attributes.EntityAttribute", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", null)
                        .WithMany("BaseAttributes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("CharacterAction")
                        .HasForeignKey("Domain.Models.CharacterActions.CharacterAction", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", b =>
                {
                    b.HasOne("Domain.Models.CharacterActions.CharacterAction", null)
                        .WithOne("ActionDetails")
                        .HasForeignKey("Domain.Models.CharacterActions.CharacterActionDetails.ActionDetails", "CharacterActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.GatheringNodes.GatheringNode", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("Domain.Models.Entities.Characters.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("Domain.Models.Inventories.Inventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Models.Inventories.InventoryItem", b =>
                {
                    b.HasOne("Domain.Models.Inventories.Inventory", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableEntry", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", null)
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.HasOne("Domain.Models.Regions.Region", null)
                        .WithMany("Areas")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.AreaCreature", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", null)
                        .WithMany("Creatures")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Creatures.Creature", null)
                        .WithMany()
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Users.IPAddresses.IPAddress", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany("IPAddresses")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Domain.Models.Users.Transactions.Transaction", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("EntityEssence", b =>
                {
                    b.HasOne("Domain.Models.Entities.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Essences.Essence", null)
                        .WithMany()
                        .HasForeignKey("EssenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.CombatActionDetails", b =>
                {
                    b.HasOne("Domain.Models.Regions.Areas.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterActionDetails.GatheringActionDetails", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.HasOne("Domain.Models.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Entities.Creatures.Creature", b =>
                {
                    b.HasOne("Domain.Models.LootTables.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Domain.Models.Items.EssenceItem", b =>
                {
                    b.HasOne("Domain.Models.Essences.Essence", "Essence")
                        .WithMany("EssenceItems")
                        .HasForeignKey("EssenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essence");
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTableItem", b =>
                {
                    b.HasOne("Domain.Models.Items.Item", "Item")
                        .WithMany("LootTablesItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Models.CharacterActions.CharacterAction", b =>
                {
                    b.Navigation("ActionDetails");
                });

            modelBuilder.Entity("Domain.Models.Entities.Entity", b =>
                {
                    b.Navigation("BaseAttributes");
                });

            modelBuilder.Entity("Domain.Models.Essences.Essence", b =>
                {
                    b.Navigation("EssenceItems");
                });

            modelBuilder.Entity("Domain.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Domain.Models.Items.Item", b =>
                {
                    b.Navigation("LootTablesItems");
                });

            modelBuilder.Entity("Domain.Models.Regions.Areas.Area", b =>
                {
                    b.Navigation("Creatures");
                });

            modelBuilder.Entity("Domain.Models.Regions.Region", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Domain.Models.Users.AppUser", b =>
                {
                    b.Navigation("IPAddresses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Domain.Models.Entities.Characters.Character", b =>
                {
                    b.Navigation("CharacterAction");

                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.LootTables.LootTable", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
