// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Chat;

#nullable disable

namespace Persistence.Chat.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Chats.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer");

                    b.Property<string>("ContextKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedItemJson")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderTitleDisplayName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetCharacterName")
                        .HasColumnType("text");

                    b.Property<string>("TargetCharacterTitleDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SenderId", "IsSystemGenerated", "SentAt", "Id");

                    b.HasIndex("ChannelType", "SenderId", "IsSystemGenerated", "SentAt", "ContextKey")
                        .HasDatabaseName("IX_ChatMessages_SharedChannelEvidence");

                    b.HasIndex("ChannelType", "SenderId", "TargetCharacterId", "IsSystemGenerated", "SentAt", "Id")
                        .HasDatabaseName("IX_ChatMessages_DirectConversationForward");

                    b.HasIndex("ChannelType", "TargetCharacterId", "SenderId", "IsSystemGenerated", "SentAt", "Id")
                        .HasDatabaseName("IX_ChatMessages_DirectConversationReverse");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Domain.Models.Chats.ChatModerationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RestrictionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RestrictionId");

                    b.HasIndex("TargetCharacterId", "OccurredAt");

                    b.ToTable("ChatModerationActions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Chats.ChatRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedBySubject")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetCharacterId", "RevokedAt", "ExpiresAt");

                    b.ToTable("ChatRestrictions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Chats.RaidChatChannel", b =>
                {
                    b.Property<Guid>("RaidRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaidRunId");

                    b.HasIndex("IsOpen", "UpdatedAt");

                    b.ToTable("RaidChatChannels", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Chats.RaidChatMembership", b =>
                {
                    b.Property<Guid>("RaidRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("RaidRunId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("RaidChatMemberships", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Chats.RaidChatMembership", b =>
                {
                    b.HasOne("Domain.Models.Chats.RaidChatChannel", "Channel")
                        .WithMany("Memberships")
                        .HasForeignKey("RaidRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Domain.Models.Chats.RaidChatChannel", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
