# syntax=docker/dockerfile:1
### STAGE 1: Build ###
FROM node:22-alpine AS angular
WORKDIR /ng-app
COPY package*.json .
COPY src/environments/environment.ts ./

ARG BUILD_VERSION
RUN sed -i "s/buildversion/${BUILD_VERSION}/g" environment.ts

RUN npm ci
COPY . .
RUN cp environment.ts src/environments/environment.ts && npm run build

### STAGE 2: Run ###
FROM nginx:alpine
EXPOSE 80
ARG name
RUN rm -rf /usr/share/nginx/html/*
COPY --from=angular /ng-app/dist/$name/browser /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
RUN nginx -t

# When the container starts, replace the env.js with values from environment variables
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
