namespace Domain.Models.Achievements;

public enum AchievementRequirementType
{
    AccountCreatedOrFirstCharacterCreated = 0,
    CharacterLevelReached = 1,
    AchievementPointsReached = 2,
    MonstersDefeated = 3,
    CreatureFamilyDefeated = 4,
    PlayerDefeats = 5,
    WinCombatBelowHealthPercent = 6,
    LoseToSpecificCreatureWhileOverpowered = 7,
    EssencesAbsorbed = 8,
    EquippedEssenceCountReached = 9,
    UniqueEssencesArchived = 10,
    EssencesAscended = 11,
    EssencesAscendedToTier = 12,
    EssenceCollectionCompleted = 13,
    DungeonRunsStarted = 14,
    DungeonRunsCompleted = 15,
    SpecificDungeonCompleted = 16,
    SpecificDungeonBossDefeated = 17,
    DungeonCompletedWithoutDefeat = 18,
    DungeonCompletedWithoutRetreat = 19,
    DungeonTrapsTriggered = 20,
    ColosseumBattlesCompleted = 28,
    ColosseumBattlesWon = 29,
    DefeatColosseumOpponentRatingAbove = 30,
    ColosseumWinStreak = 31,
    WinColosseumAfterLosingStreak = 32,
    PropheciesCompleted = 33,
    WeeklyProphecyCycleCompleted = 34,
    GuildJoined = 35,
    GuildOrdersCompleted = 36,
    GuildMissionsCompleted = 37,
    GuildSuppliesGenerated = 38,
    MarketplaceSalesCompleted = 39,
    SoulstoneUpgradesPurchased = 40,
    AllSoulstoneUpgradesMaxed = 41,
    DungeonMasteryLevelReached = 42,
    AchievementsUnlocked = 44,
    NonHiddenAchievementsCompleted = 45,
    TitlesUnlocked = 46,
    ColosseumTournamentsCompleted = 47,
    ColosseumTournamentsWon = 48,
    ChampionMarketPurchases = 49,
    DungeonCompletedWithoutWeapon = 50
}
