<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeepCloner" Version="0.10.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="WebSockets\" />
  </ItemGroup>

</Project>
