name: "Helm Package and Push Action"
description: "Packages Helm charts and pushes them to a container registry."

inputs:
  containerRegistry:
    description: "Container registry name."
    required: true
  registryUsername:
    description: "Container registry username."
    required: true
  registryPassword:
    description: "Container registry password."
    required: true
  version:
    description: "Helm chart version."
    required: true
  tag:
    description: "Application version."
    required: true
  workingDirectory:
    description: "Working directory."
    required: false
    default: "legends-legacy/ADS/deploy"

runs:
  using: "composite"
  steps:
    - name: Install Helm
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Helm OCI Enable
      shell: bash
      run: |
        helm repo add oci

    - name: Helm Login
      if: ${{ success() && github.event_name != 'pull_request' }}
      shell: bash
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username "${{ github.actor }}" --password-stdin

    - name: Package Helm Chart
      shell: bash
      run: |
        helm package ./path/to/chart \
          --version ${{ inputs.version }} \
          --app-version ${{ inputs.tag }}

    - name: Push Helm Chart
      shell: bash
      run: |
        helm push ./ll-backend-${{ inputs.version }}.tgz oci://ghcr.io/{{ github.repository }}/helm-charts
