"""Reproduce the 2026-09-25 attribute review's arithmetic and content inventory.

Analysis only: no combat simulator, database, random sampling, or game mutations.
Run with Python 3.10+; --write refreshes the adjacent generated evidence Markdown.
Without --write, fail if that evidence differs from the current checkout.
"""
from pathlib import Path
from collections import Counter
from decimal import Decimal, ROUND_HALF_UP
import argparse
import hashlib
import json
import math
import re

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "LL/src/API/API.LL/Data"
DOMAIN = ROOT / "LL/src/Core/Domain"
OUT = Path(__file__).with_name("attribute-equipment-evidence-2026-09-25.md")


def read_json(name):
    return json.loads((DATA / name).read_text(encoding="utf-8-sig"))


catalog = (DOMAIN / "Models/Items/Equipments/Progression/EquipmentStatBudgetCatalog.cs").read_text()
costs = {k: float(v) for k, v in re.findall(
    r"\[AttributeType\.(\w+)\] = (?:Flat|Percentage)\(([\d.]+)d", catalog)}
costs.update(Armor=0.9, Resistance=0.9)
assert len(costs) == 18
assert "TypedMitigationHalfCapNormalizedRating = 165d" in catalog
assert "TypedMitigationRatingExponent = 1.1d" in catalog
curve = (DOMAIN / "Models/Items/Equipments/Progression/EquipmentTierBudgetCurve.cs").read_text()
assert "TierTenBudget = 1_520d" in curve and "CharacterLevelsPerEquipmentTier = 50" in curve


def scale(t):
    return 15.2 ** ((t - 1) / 9)


def mitigation(r):
    return .8 * (1 - .5 ** ((max(0, r) / 165) ** 1.1))


def proposed_mitigation(r):
    return .8 * max(0, r) / (max(0, r) + 165)


def inverse(d):
    return 165 * (-math.log2(1 - d / .8)) ** (1 / 1.1) if d else 0


def penetration_gain(defense, p):
    return (1 - mitigation(inverse(defense) * (1 - min(60, p) / 100))) / (1 - defense)


def quantize(stat, value):
    precision = 0 if stat == "MaxHealth" else 2
    return float(Decimal(str(value)).quantize(Decimal(10) ** -precision, rounding=ROUND_HALF_UP))


def table(headers, rows):
    def cell(v):
        return f"{v:.4f}" if isinstance(v, float) else str(v)
    return ["| " + " | ".join(map(cell, headers)) + " |",
            "| " + " | ".join("---" for _ in headers) + " |"] + [
        "| " + " | ".join(map(cell, row)) + " |" for row in rows] + [""]


def build():
    lines = ["# Attribute and equipment review: reproducible evidence", "",
             "Generated by `attribute-equipment-calculations.py`. These are analytic calculations and authored-content counts, not observed player outcomes or full-engine simulations.", ""]
    starters = read_json("equipment/equipment-starters.v1.json")
    styles = read_json("equipment/equipment-styles.v1.json")
    abilities = read_json("combat/abilities.json")
    essences = read_json("essences/essences.json")["essences"]
    ability_ids = {e[key] for e in essences for key in ("activeAbilityId", "passiveAbilityId")}
    selected = [a for a in abilities if a["id"] in ability_ids]
    effects = [e for a in selected for e in a.get("effects", [])]
    statuses = read_json("combat/statuses.json")
    lines += ["## Content inventory", "", f"{len(starters['items'])} base archetypes; {len(styles)} equipment styles; {len(essences)} Essences; {len(selected)} unique directly referenced active/passive abilities; {len(abilities)} total ability definitions; {len(effects)} direct effects on those Essence abilities; {len(statuses)} custom statuses.", "",
              "Counts exclude effects reached through other statuses/summons; they measure authored coverage, not encounter frequency.", ""]
    lines += table(["Effect operation", "Count"], sorted(Counter(e["operation"] for e in effects).items()))
    lines += table(["Direct scaling attribute", "Count"], sorted(Counter(e.get("scalingAttribute", "none") for e in effects).items()))
    stat_counts = Counter(e["attribute"] for e in effects if "attribute" in e)
    set_counts = Counter(m["attributeType"] for s in read_json("equipment/equipment-sets.v1.json")
                         for b in s["bonuses"] for m in b.get("attributeModifiers", []))
    lines += table(["Attribute", "Base archetypes", "Styles", "Essence effects modifying it", "Set stat entries"], [
        [k, sum(k in x["statWeights"] for x in starters["items"]),
         sum(k in x["statWeights"] for x in styles), stat_counts[k], set_counts[k]] for k in costs])
    lines += ["## All base equipment profiles", "", "Common, Standard, tier 1, rank 0, roll 1, no style. All authored attack interval and damage multipliers are 1. Values below reproduce the uncapped allocator branch and canonical quantization.", ""]
    rows = []
    for item in starters["items"]:
        b = 200 if item["equipmentType"] == "TwoHanded" else 100
        total = sum(item["statWeights"].values())
        stats = {k: quantize(k, b * w / total / costs[k]) for k, w in item["statWeights"].items()}
        rows.append([item["id"], item["equipmentType"], ", ".join(f"{k}={v:g}" for k,v in stats.items())])
    lines += table(["Archetype", "Type", "Materialized stats"], rows)
    lines += ["## Equipment style pools", "", "15% additional budget; weights below are shares of that bonus. Set abilities have additional value not charged to the stat budget.", ""]
    lines += table(["Style", "Weights", "Compatible archetypes"], [[s["id"], json.dumps(s["statWeights"], separators=(",", ":")), ", ".join(s["compatibleArchetypeIds"])] for s in styles])
    lines += ["## Marginal value per equal normalized budget", "",
              "Each row isolates one attribute. Reference: tier 1, Power 20, Health 2000, Armor/Resistance 165 normalized rating, Crit Chance 0 (20% only when measuring Crit Damage), Crit Damage 100, all other percentages 0. No rounding, cooldown tick ceilings, other-stat feedback, overheal, or event triggers in this smooth screen. Gains are relative to the start of each interval; intervals spend 0–10, 10–20, 20–70 additional budget. DPS/HPS/EHP are distinct objectives, not interchangeable units.", ""]
    funcs = {
        "Power": (lambda x: (20 + x / costs["Power"]) / 20, "Power-scaled output"),
        "MaxHealth": (lambda x: (2000 + x / costs["MaxHealth"]) / 2000, "EHP"),
        "Armor": (lambda x: 1 / (1 - mitigation(165 + x / .9)), "Physical EHP"),
        "Resistance": (lambda x: 1 / (1 - mitigation(165 + x / .9)), "Magical EHP"),
        "CritChance": (lambda x: 1 + min(100, x / 6) / 100, "Eligible direct output"),
        "CritDamage": (lambda x: 1 + .2 * min(500, 100 + x / 2.2) / 100, "Eligible output at 20% crit"),
        "ArmorPenetration": (lambda x: penetration_gain(.4, x / 3.5), "Physical output vs 40% defense"),
        "MagicPenetration": (lambda x: penetration_gain(.4, x / 4), "Magical output vs 40% defense"),
        "DodgeChance": (lambda x: 1 / (1 - min(40, x / 30) / 100), "Dodgeable-hit EHP"),
        "BlockChance": (lambda x: 1 / (1 - min(60, x / 5.7) / 200), "Blockable-hit EHP"),
        "DamageReduction": (lambda x: 1 / (1 - min(40, x / 6) / 100), "Damage-path EHP"),
        "HealingPowerPercent": (lambda x: 1 + min(300, x / 4.5) / 100, "Eligible healing"),
        "Cooldown": (lambda x: 1 / (1 - min(40, x / 7.5) / 100), "Cooldown-limited rate"),
        "AttackSpeed": (lambda x: min(4, 1 + x / 100), "Basic attack rate"),
    }
    rows = []
    for k in costs:
        if k in funcs:
            f, objective = funcs[k]
            values = [100 * (f(b) / f(a) - 1) for a,b in [(0,10),(10,20),(20,70)]]
            rows.append([k, objective + " (%)", *values])
        elif k == "HealthRegeneration":
            rows.append([k, "Additional HP/s (absolute)", 10/15, 10/15, 50/15])
        elif k == "LifeSteal":
            rows.append([k, "Additional HP/s per 100 eligible DPS", 10/8, 10/8, 50/8])
        else:
            rows.append([k, "Custom-status seconds saved from 10s; standard=0", 10/8.2, 10/8.2, (min(80,70/.82)-20/.82)/10])
    lines += table(["Attribute", "Objective", "First 10 B", "Next 10 B", "Next 50 B"], rows)
    lines += ["## Raw-point increments", "", "Same reference and objectives as above, but increments are raw stat units (percentage points where applicable), not equal budgets. Armor uses normalized rating. Regeneration and Lifesteal are absolute outputs. Resistance duration entries describe custom statuses only; standard-condition savings remain zero.", ""]
    rows = []
    for k in costs:
        if k in funcs:
            f, objective = funcs[k]
            values = [100*(f(b*costs[k])/f(a*costs[k])-1) for a,b in [(0,10),(10,20),(20,70)]]
            rows.append([k, *values])
        elif k == "HealthRegeneration": rows.append([k, 2., 2., 10.])
        elif k == "LifeSteal": rows.append([k, 10., 10., 50.])
        else: rows.append([k, 1., 1., 5.])
    lines += table(["Attribute", "+0–10 units", "+10–20 units", "+20–70 units"], rows)
    lines += ["Threat has no item cost. At a fixed median threat of 100, attention weights for Threat 100/110/120/170 are " + ", ".join(f"{(t/100)**2.5:.4f}" for t in (100,110,120,170)) + "; actual target probability divides by the sum of all eligible weights and uses taunt/stealth rules.", ""]
    lines += ["## Defense and penetration", ""]
    lines += table(["Normalized rating", "Current mitigation %", "Current EHP multiplier", "Proposed mitigation %", "Proposed EHP multiplier"], [[r, 100*mitigation(r), 1/(1-mitigation(r)),100*proposed_mitigation(r),1/(1-proposed_mitigation(r))] for r in (0,10,20,55,100,165,330,660,1000)])
    lines += table(["Target mitigation %", "+10% penetration output gain %", "+1% penetration gain %"], [[d*100,100*(penetration_gain(d,10)-1),100*(penetration_gain(d,1)-1)] for d in (.1,.2,.4,.6,.75,.79)])
    lines += ["## Progression stress fixture", "", "Hypothetical full eight-slot loadout using three Medium armor pieces, Band, Amulet, Vial and Greatsword; Common/Standard/rank 0/no styles. This is an analytic fixture, not a sampled player. Tier 10 is extrapolation, not an authored Region 10 encounter.", ""]
    ids = ["plain.medium_helm","plain.medium_mail","plain.medium_greaves","plain.band","plain.amulet","plain.vial","plain.greatsword"]
    items = {x["id"]: x for x in starters["items"]}
    weights = Counter()
    for id_ in ids:
        it=items[id_];b=200 if it["equipmentType"]=="TwoHanded" else 100
        for k,v in it["statWeights"].items(): weights[k]+=b*v
    rows=[]
    for level,t in [(1,1),(100,3),(250,6),(450,10),(451,10),(500,10)]:
        s=scale(t); expected=(level-1)//50+1
        p=10+.25*(level-1)+weights["Power"]*s/costs["Power"]
        hp=140+20*(level-1)+weights["MaxHealth"]*s/costs["MaxHealth"]
        r=weights["Armor"]*s/costs["Armor"]/scale(expected)
        regen=2+weights["HealthRegeneration"]*s/3
        rows.append([level,t,s,p,hp,100*mitigation(r),regen,weights["CritChance"]/6])
    lines += table(["Level", "Item tier", "Tier scale", "Power", "Health", "Armor/Resistance %", "Regen HP/5s", "Crit %"], rows)
    lines += [f"Tier growth = {scale(2):.8f}. A fixed 165 normalized-rating loadout crosses a character tier boundary: 40% becomes {100*mitigation(165/scale(2)):.4f}%; typed EHP falls by {100*(1-(1-.4)/(1-mitigation(165/scale(2)))):.4f}% at unchanged Health.", ""]
    lines += ["## Item and outcome examples", ""]
    rows=[]
    for model,cc,attack in [("Current",.05,.30),("Proposed",.075,.15)]:
        for fraction in (.7,.15):
            rows.append([model,fraction,100*cc,100*attack*fraction])
    lines += table(["Rules", "Basic-linked output fraction", "Shortsword total output gain %", "Dagger total output gain %"],rows)
    rows=[]
    for model,fn,core in [("Current",mitigation,1),("Proposed",proposed_mitigation,.7)]:
        for item_id in ("plain.heavy_helm","plain.light_hood"):
            w=items[item_id]["statWeights"]
            p=20+100*core*w.get("Power",0)/22.5
            hp=2000+100*core*w["MaxHealth"]/.185
            r=100+100*core*w["Armor"]/.9
            # Proposed uses the same 30-budget, +10% Block choice on both helmets.
            block=.1 if model=="Proposed" else 0
            rows.append([model,item_id,p,hp,100*fn(r),hp/(1-fn(r))/(1-block/2)])
    lines += table(["Rules", "Item", "Total Power", "Total Health", "Typed mitigation %", "EHP vs blockable typed hits"],rows)
    # Honest provenance: all current arithmetic constants above are source-checked;
    # proposal constants are the review's explicit candidate, not game settings.
    sources = [DOMAIN / "Models/Attributes/AttributeCombatRules.cs",
               DOMAIN / "Components/Attributes/AttributeCalculator.cs",
               DOMAIN / "Models/Items/Equipments/Progression/EquipmentStatBudgetCatalog.cs",
               DOMAIN / "Models/Items/Equipments/Progression/EquipmentTierBudgetCurve.cs",
               DATA / "equipment/equipment-starters.v1.json", DATA / "equipment/equipment-styles.v1.json",
               DATA / "equipment/equipment-sets.v1.json", DATA / "combat/abilities.json",
               DATA / "combat/statuses.json", DATA / "combat/summons.json",
               DATA / "essences/essences.json", DATA / "combat-styles/combat-styles.v1.json",
               ROOT / "LL/src/Infrastructure/Service/Services.LL/Combat/Engine/FastCombatEngine.cs"]
    lines += ["## Source fingerprints", ""]
    lines += table(["Source", "SHA-256"], [[p.relative_to(ROOT).as_posix(),hashlib.sha256(p.read_bytes()).hexdigest()] for p in sources])
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write",action="store_true")
    args=parser.parse_args()
    result=build()
    if args.write:
        OUT.write_text(result,encoding="utf-8")
        print(f"Wrote {OUT}")
    else:
        assert OUT.read_text(encoding="utf-8") == result, "Evidence differs; inspect source changes before refreshing."
        print("PASS: evidence tables and source fingerprints reproduce exactly.")
