name: LL backend - build workflow

on:
  workflow_call:
    inputs:
      build_configuration:
        description: "Build configuration (e.g., Debug or Release)."
        required: false
        default: "Release"
        type: string
      projects_filter:
        description: "Path or pattern to the projects to restore and build."
        required: true
        type: string
      project_name:
        description: "Project name."
        required: true
        type: string
      dotnet_version:
        description: ".NET SDK version used to restore and build the project."
        required: false
        default: "10.x"
        type: string
      version:
        description: "Version number."
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "${{ inputs.dotnet_version }}"

      - name: Restore ${{ inputs.project_name }}
        run: |
          dotnet restore "${{ inputs.projects_filter }}"

      - name: Build ${{ inputs.project_name }}
        run: |
          dotnet build "${{ inputs.projects_filter }}" \
            --configuration "${{ inputs.build_configuration }}" \
            --no-restore \
            -p:Version="${{ inputs.version }}" \
            -p:InformationalVersion="${{ inputs.version }} ${{ github.sha }})"
