name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "releases/**"
    paths:
      - "LL/**"
      - "!LL/src/Presentation/ll/**"

env:
  buildConfiguration: Release

  major: 0
  minor: 0
  patch: ${{ github.run_number }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag: ${{ steps.set_tag.outputs.tag }}
      tagid: ${{ steps.set_tagid.outputs.tagid }}
      tagcommit: ${{ steps.set_tagid.outputs.tagcommit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create version variable
        id: set_version
        run: |
          echo "version=${{env.major}}.${{env.minor}}.${{env.patch}}" >> $GITHUB_ENV
          echo "::set-output name=version::${{env.major}}.${{env.minor}}.${{env.patch}}"

      - name: Set tag variable
        id: set_tag
        shell: bash
        run: |
          echo "GITHUB_REF is $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            tag="main-${{ env.version }}"
          elif [[ "$GITHUB_REF" == refs/heads/releases/* ]]; then
            tag="release-${{ env.version }}"
          else
            tag="${{ env.version }}"
          fi
          echo "::set-output name=tag::$tag"
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Set tagid and tagcommit
        id: set_tagid
        run: |
          echo "tagid=build-${{ github.run_id }}" >> $GITHUB_ENV
          echo "tagcommit=commit-${{ github.sha }}" >> $GITHUB_ENV
          echo "::set-output name=tagid::build-${{ github.run_id }}"
          echo "::set-output name=tagcommit::commit-${{ github.sha }}"

      - name: Output Tags
        run: |
          echo "Version Tag: ${{ env.tag }}"
          echo "Build ID Tag: ${{ env.tagid }}"
          echo "Commit Tag: ${{ env.tagcommit }}"

  build:
    needs: setup
    uses: ./.github/workflows/LL-backend-build.yml
    with:
      projects_filter: "LL/LegendsLegacy.sln"
      project_name: "LL"
      version: ${{ needs.setup.outputs.version }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Publish and Push
        uses: ./.github/actions/build-and-push-docker
        with:
          tag: ${{ env.TAG }}
          version: ${{ needs.setup.outputs.version }}
          workingDirectory: "LL"
          buildScript: "./build/build-ll.ps1"
          token: ${{ secrets.GITHUB_TOKEN }}

  helm:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm Package and Push
        uses: ./.github/actions/build-and-push-helm
        with:
          containerRegistry: ${{ env.CONTAINER_REGISTRY }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          version: ${{ needs.setup.outputs.version }}
          tag: ${{ env.TAG }}
          workingDirectory: "LL/deploy"
          token: ${{ secrets.GITHUB_TOKEN }}

  # version_bump:
  #   needs: helm
  #   uses: ./.github/workflows/version-bump.yml
  #   with:
  #     tag: ${{ needs.build_and_test.outputs.TAG }}
  #     version: ${{ needs.setup.outputs.VERSION }}
  #     versionfile: "deploy/versions/ll-backend.version"
  #     build_configuration:
  #   secrets:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     INFRASTRUCTURE_REPO: "your-org/infrastructure"
