name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "releases/**"
    paths:
      - "LL/**"
      - "!LL/src/Presentation/ll/**"

env:
  buildConfiguration: Release

  major: 0
  minor: 0
  patch: ${{ github.run_number }}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create version variable
        run: |
          echo "version=${{env.major}}.${{env.minor}}.${{env.patch}}" >> $GITHUB_ENV

      - name: Set tag variable

        shell: bash
        run: |
          echo "GITHUB_REF is $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            tag="main-${{ env.version }}"
          elif [[ "$GITHUB_REF" == refs/heads/releases/* ]]; then
            tag="release-${{ env.version }}"
          else
            tag="${{ env.version }}"
          fi
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Set tagid and tagcommit
        run: |
          echo "tagid=build-${{ github.run_id }}" >> $GITHUB_ENV
          echo "tagcommit=commit-${{ github.sha }}" >> $GITHUB_ENV

      # Optionally, use the computed tags
      - name: Output Tags
        run: |
          echo "Version Tag: ${{ env.tag }}"
          echo "Build ID Tag: ${{ env.tagid }}"
          echo "Commit Tag: ${{ env.tagcommit }}"

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build backend
        uses: ./.github/actions/backend-build
        with:
          projects_filter: "legends-legacy/LL/LL.sln"
          test_projects_filter: "legends-legacy/LL/LL.sln"
          test_run_settings_file: "legends-legacy/LL/CodeCoverage.runsettings"
          project_name: "LL"
          version: ${{ env.VERSION }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Docker Publish and Push
        uses: ./.github/actions/docker.yml
        with:
          tag: ${{ env.TAG }}
          version: ${{ env.VERSION }}
          workingDirectory: "legends-legacy"
          buildScript: "./build/build-ll.ps1"

  helm:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Helm Package and Push
        uses: ./.github/actions/helm.yaml
        with:
          containerRegistry: ${{ env.CONTAINER_REGISTRY }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          version: ${{ env.VERSION }}
          tag: ${{ env.TAG }}
          workingDirectory: "legends-legacy/LL/deploy"

  # version_bump:
  #   needs: helm
  #   uses: ./.github/workflows/version-bump.yml
  #   with:
  #     tag: ${{ needs.build_and_test.outputs.TAG }}
  #     version: ${{ needs.build_and_test.outputs.VERSION }}
  #     versionfile: "deploy/versions/ll-backend.version"
  #     build_configuration:
  #   secrets:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     INFRASTRUCTURE_REPO: "your-org/infrastructure"
