name: Build LL Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "releases/**"
    paths:
      - "LL/src/Presentation/ll"

env:
  buildConfiguration: Release
  dockerfilePath: "LL/src/Presentation/ll/"
  major: 0
  minor: 0
  patch: ${{ github.run_number }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag: ${{ steps.set_tag.outputs.tag }}
      tagid: ${{ steps.set_tagid.outputs.tagid }}
      tagcommit: ${{ steps.set_tagid.outputs.tagcommit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create version variable
        id: set_version
        run: |
          echo "version=${{env.major}}.${{env.minor}}.${{env.patch}}" >> $GITHUB_ENV
          echo "version=${{env.major}}.${{env.minor}}.${{env.patch}}" >> $GITHUB_OUTPUT

      - name: Set tag variable
        id: set_tag
        shell: bash
        run: |
          echo "GITHUB_REF is $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            tag="main-${{ env.version }}"
          elif [[ "$GITHUB_REF" == refs/heads/releases/* ]]; then
            tag="release-${{ env.version }}"
          else
            tag="${{ env.version }}"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Set tagid and tagcommit
        id: set_tagid
        run: |
          echo "tagid=build-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "tagcommit=commit-${{ github.sha }}" >> $GITHUB_OUTPUT

  docker:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image using pwsh
        shell: pwsh
        run: |
          docker build \
            --file "LL/src/Presentation/ll/dockerfile" \
            --build-arg name=ll \
            --build-arg BUILD_VERSION=${{ needs.setup.outputs.version }} \
            --progress=plain \
            --tag ll-frontend:${{ needs.setup.outputs.TAG }} \
            LL/src/Presentation/ll

      - name: Docker Login
        if: ${{ success() && github.event_name != 'pull_request' }}
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: set lower case owner name
        shell: bash
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Push Docker images
        if: github.event_name != 'pull_request'
        run: |
          docker push ghcr.io/${{ env.OWNER_LC }}/ll-frontend:${{ needs.setup.outputs.TAG }}

      - name: Helm Package and Push
        uses: ./.github/actions/build-and-push-helm
        with:
          version: ${{ needs.setup.outputs.version }}
          tag: ${{ needs.setup.outputs.tag }}
          workingDirectory: "LL/src/Presentation/ll/deploy/ll-frontend"
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: "ll-frontend"

  # version_bump:
  #   needs: helm
  #   uses: ./.github/workflows/version-bump.yml
  #   with:
  #     tag: ${{ needs.setup.outputs.TAG }}
  #     version: ${{ needs.setup.outputs.VERSION }}
  #     versionfile: "deploy/versions/ll-backend.version"
  #     build_configuration:
  #   secrets:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     INFRASTRUCTURE_REPO: "your-org/infrastructure"
